project_id = "plfpczvnqmvqpmsbjrra"

[functions.criar-empresa-trial]
verify_jwt = false

[functions.aprovar-empresa]
verify_jwt = false

[functions.processar-comprovante-whatsapp]
verify_jwt = false

[functions.calcular-distancia]
verify_jwt = false

[functions.calcular-pedagios]
verify_jwt = false

[functions.calcular-pedagios-brasil]
verify_jwt = false

[functions.calcular-rota-google]
verify_jwt = false

[functions.calcular-rota-brasil]
verify_jwt = false

[functions.processar-documento-estoque]
verify_jwt = false

[functions.alterar-senha-motorista]
verify_jwt = false

[functions.processar-comprovante]
verify_jwt = false

[functions.consultar-cnpj]
verify_jwt = false

[functions.consultar-cep]
verify_jwt = false